#!/bin/sh
# ═══════════════════════════════════════════════════════════════════════════
# template-init.sh - Initialize new project from cosmicringforge template
# ═══════════════════════════════════════════════════════════════════════════
#
# Usage: ./scripts/template-init.sh <project-name>
#
# This script:
#   1. Verifies Ring 0 tools build
#   2. Bootstraps schemagen (self-hosting)
#   3. Verifies vendor libraries
#   4. Runs regen-and-diff gate
#   5. Creates project skeleton
#
# Requirements: C compiler, sh, make
# ═══════════════════════════════════════════════════════════════════════════

set -e

# ── Configuration ──────────────────────────────────────────────────────────

PROJECT="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors (if terminal supports)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' NC=''
fi

# ── Functions ──────────────────────────────────────────────────────────────

log_info()  { printf "${GREEN}[INFO]${NC} %s\n" "$1"; }
log_warn()  { printf "${YELLOW}[WARN]${NC} %s\n" "$1"; }
log_error() { printf "${RED}[ERROR]${NC} %s\n" "$1"; }

check_tool() {
    if command -v "$1" >/dev/null 2>&1; then
        log_info "Found: $1"
        return 0
    else
        log_warn "Missing: $1"
        return 1
    fi
}

# ── Argument Validation ────────────────────────────────────────────────────

if [ -z "$PROJECT" ]; then
    cat <<'EOF'
Usage: ./scripts/template-init.sh <project-name>

Initializes a new project from the cosmicringforge template.

Examples:
    ./scripts/template-init.sh my-embedded-app
    ./scripts/template-init.sh ../../new-project
EOF
    exit 1
fi

# ── Main Flow ──────────────────────────────────────────────────────────────

echo "═══════════════════════════════════════════════════════════════════════"
echo " MBSE Stacks Template Initialization"
echo " Project: $PROJECT"
echo "═══════════════════════════════════════════════════════════════════════"
echo

cd "$ROOT_DIR"

# Step 1: Verify toolchain
log_info "Step 1: Verifying toolchain..."
check_tool cc || check_tool gcc || check_tool clang || {
    log_error "No C compiler found. Install gcc or clang."
    exit 1
}
check_tool make || {
    log_error "make not found. Install make."
    exit 1
}
check_tool sh || {
    log_error "sh not found. This shouldn't happen."
    exit 1
}

# Step 2: Build Ring 0 generators
log_info "Step 2: Building Ring 0 generators..."
if [ -d "strict-purist/gen" ]; then
    make -C strict-purist/gen all 2>/dev/null || {
        log_warn "Ring 0 generators not yet implemented, skipping"
    }
else
    log_warn "strict-purist/gen/ not found, skipping generator build"
fi

# Step 3: Verify vendor libraries
log_info "Step 3: Verifying vendor libraries..."
VENDOR_DIR="strict-purist/vendor"
for lib in sqlite lemon nuklear yyjson civetweb; do
    if [ -d "$VENDOR_DIR/$lib" ]; then
        if [ -f "$VENDOR_DIR/$lib/Makefile" ]; then
            make -C "$VENDOR_DIR/$lib" clean all 2>/dev/null && \
                log_info "  $lib: OK" || \
                log_warn "  $lib: build failed (may need configuration)"
        else
            log_info "  $lib: present (no Makefile)"
        fi
    else
        log_warn "  $lib: not found"
    fi
done

# Step 4: Check if APE profile available
log_info "Step 4: Checking APE (Cosmopolitan) support..."
if [ -d "$VENDOR_DIR/cosmopolitan" ] || command -v cosmocc >/dev/null 2>&1; then
    log_info "  APE support: available"
    APE_AVAILABLE=1
else
    log_warn "  APE support: not available (cosmocc not found)"
    APE_AVAILABLE=0
fi

# Step 5: Create project directory
log_info "Step 5: Creating project skeleton..."
if [ -d "$PROJECT" ]; then
    log_error "Directory $PROJECT already exists"
    exit 1
fi

mkdir -p "$PROJECT"/{src,specs,gen,build,tests}

# Copy template files
if [ -d "templates/project" ]; then
    cp -r templates/project/* "$PROJECT/"
fi

# Create minimal Makefile
cat > "$PROJECT/Makefile" << 'MAKEFILE'
# ════════════════════════════════════════════════════════════════════════════
# Project Makefile - Generated by cosmicringforge template
# ════════════════════════════════════════════════════════════════════════════

PROJECT ?= $(notdir $(CURDIR))
PROFILE ?= portable

CC ?= cc
CFLAGS ?= -O2 -Wall -Wextra -std=c11

# Paths
SRC_DIR := src
GEN_DIR := gen
BUILD_DIR := build
SPECS_DIR := specs

# Sources
SRCS := $(wildcard $(SRC_DIR)/*.c) $(wildcard $(GEN_DIR)/*.c)
OBJS := $(SRCS:%.c=$(BUILD_DIR)/%.o)

# ── Main Targets ────────────────────────────────────────────────────────────

all: $(BUILD_DIR)/$(PROJECT)

$(BUILD_DIR)/$(PROJECT): $(OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

# ── Generation ──────────────────────────────────────────────────────────────

gen-schema:
	@echo "Run: schemagen $(SPECS_DIR)/*.schema -o $(GEN_DIR)/"

gen-sm:
	@echo "Run: smgen $(SPECS_DIR)/*.sm -o $(GEN_DIR)/"

regen: gen-schema gen-sm

# ── Utilities ───────────────────────────────────────────────────────────────

clean:
	rm -rf $(BUILD_DIR)

verify:
	git diff --exit-code $(GEN_DIR)/

.PHONY: all clean regen verify gen-schema gen-sm
MAKEFILE

# Create example spec
cat > "$PROJECT/specs/example.schema" << 'SCHEMA'
# Example Schema - Edit this file
# Run: make gen-schema

type ExampleConfig {
    name: string[64] [not_empty]
    enabled: i32 [default: 1]
    timeout_ms: i32 [range: 0..60000, default: 5000]
}
SCHEMA

# Create example main.c
cat > "$PROJECT/src/main.c" << 'MAIN'
/*
 * main.c - Generated by cosmicringforge template
 * Edit this file for your application entry point.
 */

#include <stdio.h>

/* Include generated types when available */
/* #include "../gen/example_types.h" */

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;

    printf("Hello from cosmicringforge template!\n");
    printf("Edit specs/example.schema and run: make gen-schema\n");

    return 0;
}
MAIN

# Create .gitignore
cat > "$PROJECT/.gitignore" << 'GITIGNORE'
# Build artifacts
build/
*.o
*.exe
*.com

# Editor
*~
*.swp
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
GITIGNORE

log_info "Project created at: $PROJECT/"

# Step 6: Summary
echo
echo "═══════════════════════════════════════════════════════════════════════"
echo " Initialization Complete"
echo "═══════════════════════════════════════════════════════════════════════"
echo
echo "Next steps:"
echo "  1. cd $PROJECT"
echo "  2. Edit specs/example.schema"
echo "  3. make gen-schema   (when schemagen is available)"
echo "  4. make"
echo
if [ "$APE_AVAILABLE" = "1" ]; then
    echo "APE builds available: make PROFILE=ape"
fi
echo
echo "Documentation:"
echo "  - TOOLING.md         - All tools and orchestration"
echo "  - RING_CLASSIFICATION.md - Ring definitions"
echo "  - CONVENTIONS.md     - Code conventions"
echo
