# ══════════════════════════════════════════════════════════════════════════════
# setup-cosmocc - Composite action for cosmocc installation
# ══════════════════════════════════════════════════════════════════════════════
#
# Usage:
#   - uses: ./.github/actions/setup-cosmocc
#
# ══════════════════════════════════════════════════════════════════════════════

name: 'Setup cosmocc'
description: 'Install Cosmopolitan C compiler for APE builds'

runs:
  using: 'composite'
  steps:
    - name: Cache cosmocc
      id: cache-cosmocc
      uses: actions/cache@v4
      with:
        path: ~/.cosmocc
        key: cosmocc-${{ runner.os }}

    - name: Install cosmocc
      if: steps.cache-cosmocc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.cosmocc
        curl -sL https://cosmo.zip/pub/cosmocc/cosmocc.zip -o /tmp/cosmocc.zip
        unzip -q /tmp/cosmocc.zip -d ~/.cosmocc

    - name: Add cosmocc to PATH
      shell: bash
      run: echo "$HOME/.cosmocc/bin" >> $GITHUB_PATH
